import { type NextPage } from 'next'
import Head from 'next/head'
import BuildCard from '../components/buildCard'
import StyleFilter from '../components/styleFilter'

export const ecoBuildType = 'Economic'
export const timingAttackBuildType = 'Timing Attack'
export const allInBuildType = 'All In'
export const cheeseBuildType = 'Cheese'
export const buildTypes = [
  ecoBuildType,
  timingAttackBuildType,
  allInBuildType,
  cheeseBuildType,
]

const BuildsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center px-4">
        <h1 className="m-8 text-2xl">Builds</h1>
        <StyleFilter />
        <BuildCard />
      </main>
    </>
  )
}

export default BuildsPage
