import { type NextPage } from 'next'
// import { signIn, signOut, useSession } from "next-auth/react";
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'
import { trpc } from '../utils/trpc'

const Home: NextPage = () => {
  const createBuild = trpc.builds.createBuild.useMutation()
  const [matchup, setMatchup] = useState('')
  const [title, setTitle] = useState('')
  const [build, setBuild] = useState('')

  async function handleSubmitBuildOrder(e: React.FormEvent) {
    e.preventDefault()
    await createBuild.mutateAsync({
      matchup,
      title,
      build,
    })
  }

  return (
    <>
      <Head>
        <title>SC2 Build Orders</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] px-4">
        <h1 className="text-xl">Welcome to SC2 Build Orders</h1>

        <Link href="/submit-build" className="m-8">
          Submit a Build
        </Link>
        <Link href="/builds" className="">
          Builds
        </Link>
      </main>
    </>
  )
}

export default Home
