import { type NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { trpc } from '../../utils/trpc'

const BuildPage: NextPage = () => {
  const { buildId } = useRouter().query as {
    buildId: string
  }

  const build = trpc.builds.getBuildByID.useQuery({
    buildId,
  })

  return (
    <>
      <Head>
        <title>View Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-auto flex flex-col gap-4 px-4 pt-24">
        <h1 className="text-4xl">{build.data?.title}</h1>
        <pre className="bg-gray-light p-4">{build.data?.build}</pre>
      </main>
    </>
  )
}

export default BuildPage
